name: ExotiaCalendar
version: 1.2
author: Exotia.net Team
website: https://exotia.net/
description: Spigot Plugin for Exotia.net daily reward system
main: net.exotia.plugins.calendar.CalendarPlugin
api-version: 1.19
softdepend: [ PlaceholderAPI, Oraxen ]
depend: [ ExotiaBridge ]